[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.1.2"
  export = ["readersguildappi"]
  icon = "docs/icon.png"
  keywords = ["Type/GraphQL","Category/Service","Internal/http"]
  name = "readersguildappi"
  org = "testaysh"
  version = "1.0.1"

